### ISSUE TITLE
[Urgent] Error in Island code for SKN 68.61 and 92.11

### ISSUE THREAD

**Issue by kodamak-hi** [ikewai/hawaii_wx_station_mgmt_container#31]
Islands seem to have mistaken labeling for
1. SKN68.61 Keahuolu 0241, labeled as MA while the surrounding stations (and presumably coordinates) correspond to BI.
2. SKN92.11 Keaau 0202, labeled as HA.
Please correct asap as this is breaking the real-time temperature workflow which depends on the master metadata to associate predictors to the correct island files.

**Comment by mattplulu** [comment]
Done! Both now island labeled as "BI"
