### ISSUE TITLE
Duplicate NWS.id for 3.9, 329.0, 109.0, 886.8

### ISSUE THREAD

**Issue by kodamak-hi** [ikewai/hawaii_wx_station_mgmt_container#32]
NWS.ids are duplicated for
3.9 Lower Kahuku CS, BI, listed as LKHH1 (this should be the correct one)
329 Lower Kahuku CS, MA, also listed as LKHH1 (I think this one has a mislabeled station name also?)

109.0 PTA RANGE 17, BI, listed as PTRH1 (I think this is correct)
886.8 Hakipuu Mauka, OA, also listed as PTRH1 (I'm not sure if this one has its own NWS.id, but I don't think it should be PTRH1).
886.1 is also listed as Waikane Hakipuu Mauka, with NWS.id HAKH1 but the coordinates from HADS (https://hads.ncep.noaa.gov//cgi-bin/hads/interactiveDisplays/displayMetaData.pl?table=dcp&nesdis_id=16C69380) match the coordinates of 886.8. I don't know which one is the actual HADS one.

**Comment by kodamak-hi** [comment]
886.8 should be HAKH1

**Comment by mattplulu** [comment]
LKHH1 removed from SKN 329
PTRH1 removed from SKN 886.8
HAKH1 added to SKN 886.8
HAKH1 removed from SKN 886.1
SKN 886.1 noted as old station location for SKN 886.8
