### ISSUE TITLE
Island codes labeled as HA again

### ISSUE THREAD

**Issue by kodamak-hi** [ikewai/hawaii_wx_station_mgmt_container#34]
2.19 and 94.6 (corresponding to 035HI and 034HI) have their islands labeled as HA instead of BI. I think there is maybe a mixed up labeling convention in the workflow.

**Comment by mattplulu** [comment]
I think Han must of accidentally used BI not HA. I will fix and contact her.

**Comment by mattplulu** [comment]
I mean used HA not BI...

**Comment by mattplulu** [comment]
Fixed.
