### ISSUE TITLE
793.1 Waimanalo Experimental Farm

### ISSUE THREAD

**Issue by aimeesch** [ikewai/hawaii_wx_station_mgmt_container#5]
Possible misnamed station.
Current Station ID: 793.1
Current lat long: 21.37, -157.72
Current Name: WAIMANALO EXPERIMENTAL FARM
Proposed correct name: KAILUA 2.2 SSE

**Comment by mattplulu** [comment]
Name changed from WAIMANALO EXPERIMENTAL FARM to KAILUA 2.2 SSE
